export const STUDENT_CONSTANTS = Object.freeze({
    ADD_OR_EDIT_MA: "SESSION_EXPIRED",
    ERROR: "ERROR",
    DELETE_CONFIRMATION: "DELETE_CONFIRMATION",
    ADD_OR_EDIT_STUDENT : "ADD_OR_EDIT_STUDENT",
    DEFAULT: "",
});
